from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MapLap(object):
    def setupUi(self, MapLap):
        MapLap.setObjectName("MapLap")
        MapLap.resize(500, 300)
        MapLap.setMinimumSize(QtCore.QSize(500, 300))
        MapLap.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MapLap.setAutoFillBackground(False)
        MapLap.setStyleSheet("background-color: rgb(180, 200, 200);")
        self.central_widget = QtWidgets.QWidget(MapLap)
        self.central_widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.central_widget.sizePolicy().hasHeightForWidth())
        self.central_widget.setSizePolicy(sizePolicy)
        self.central_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.central_widget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.central_widget.setObjectName("central_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.picture_in = QtWidgets.QFrame(self.central_widget)
        self.picture_in.setEnabled(True)
        self.picture_in.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.picture_in.setFrameShadow(QtWidgets.QFrame.Raised)
        self.picture_in.setObjectName("picture_in")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.picture_in)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plain_text_picture_in = QtWidgets.QPlainTextEdit(self.picture_in)
        self.plain_text_picture_in.setEnabled(True)
        self.plain_text_picture_in.setObjectName("plain_text_picture_in")
        self.verticalLayout.addWidget(self.plain_text_picture_in)
        self.gridLayout.addWidget(self.picture_in, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.central_widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 0, 1, 1, 1)
        self.panel_settings = QtWidgets.QTabWidget(self.central_widget)
        self.panel_settings.setMinimumSize(QtCore.QSize(141, 0))
        self.panel_settings.setMaximumSize(QtCore.QSize(141, 16777215))
        self.panel_settings.setAutoFillBackground(False)
        self.panel_settings.setObjectName("panel_settings")
        self.panel_tab = QtWidgets.QWidget()
        self.panel_tab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.panel_tab.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.panel_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.panel_tab.setAutoFillBackground(False)
        self.panel_tab.setObjectName("panel_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.panel_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cropping = QtWidgets.QPushButton(self.panel_tab)
        self.cropping.setObjectName("cropping")
        self.verticalLayout_2.addWidget(self.cropping)
        self.select_area = QtWidgets.QPushButton(self.panel_tab)
        self.select_area.setObjectName("select_area")
        self.verticalLayout_2.addWidget(self.select_area)
        self.choose_file = QtWidgets.QPushButton(self.panel_tab)
        self.choose_file.setObjectName("choose_file")
        self.verticalLayout_2.addWidget(self.choose_file)
        self.save_tex = QtWidgets.QPushButton(self.panel_tab)
        self.save_tex.setObjectName("save_tex")
        self.verticalLayout_2.addWidget(self.save_tex)
        self.save_pdf = QtWidgets.QPushButton(self.panel_tab)
        self.save_pdf.setObjectName("save_pdf")
        self.verticalLayout_2.addWidget(self.save_pdf)
        self.rotate = QtWidgets.QPushButton(self.panel_tab)
        self.rotate.setObjectName("rotate")
        self.verticalLayout_2.addWidget(self.rotate)
        self.panel_settings.addTab(self.panel_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.settings_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plain_text_settings = QtWidgets.QPlainTextEdit(self.settings_tab)
        self.plain_text_settings.setEnabled(True)
        self.plain_text_settings.setObjectName("plain_text_settings")
        self.verticalLayout_3.addWidget(self.plain_text_settings)
        self.panel_settings.addTab(self.settings_tab, "")
        self.gridLayout.addWidget(self.panel_settings, 0, 0, 1, 1)
        self.picture_out = QtWidgets.QFrame(self.central_widget)
        self.picture_out.setEnabled(True)
        self.picture_out.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.picture_out.setFrameShadow(QtWidgets.QFrame.Raised)
        self.picture_out.setObjectName("picture_out")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.picture_out)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plain_text_picture_out = QtWidgets.QPlainTextEdit(self.picture_out)
        self.plain_text_picture_out.setObjectName("plain_text_picture_out")
        self.verticalLayout_4.addWidget(self.plain_text_picture_out)
        self.gridLayout.addWidget(self.picture_out, 0, 3, 1, 1)
        MapLap.setCentralWidget(self.central_widget)

        self.retranslateUi(MapLap)
        self.panel_settings.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MapLap)

    def retranslateUi(self, MapLap):
        _translate = QtCore.QCoreApplication.translate
        MapLap.setWindowTitle(_translate("MapLap", "MapLap"))
        self.plain_text_picture_in.setPlainText(_translate("MapLap", "здесь будет исходная картинка"))
        self.cropping.setText(_translate("MapLap", "cropping"))
        self.select_area.setText(_translate("MapLap", "select area"))
        self.choose_file.setText(_translate("MapLap", "choose file"))
        self.save_tex.setText(_translate("MapLap", "save tex"))
        self.save_pdf.setText(_translate("MapLap", "save pdf"))
        self.rotate.setText(_translate("MapLap", "rotate"))
        self.panel_settings.setTabText(self.panel_settings.indexOf(self.panel_tab), _translate("MapLap", "panel"))
        self.plain_text_settings.setPlainText(_translate("MapLap", "Здесь будут размещены необходимые значения для алгоритма"))
        self.panel_settings.setTabText(self.panel_settings.indexOf(self.settings_tab), _translate("MapLap", "settings"))
        self.plain_text_picture_out.setPlainText(_translate("MapLap", "здесь будет итоговая картинка"))