# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Code Quality and Lint
      uses: ricardochaves/python-lint@v1.1.0
      with:
        python-root-list: "maplap"
        use-mypy: false
        extra-pylint-options: "--max-line-length=100 --disable=C0111"
        extra-pycodestyle-options: "--max-line-length=100"
        extra-flake8-options: "--max-line-length=100"
        extra-black-options: "--line-length 100"
        extra-mypy-options: ""
        extra-isort-options: ""
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
